# This is a basic workflow to help you get started with Actions

name: Build and deploy to surge.sh

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-deploy"
  build-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Generate 200.html
        run: cp build/index.html build/200.html
      - name: Deploy to uwork.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: "https://uwork.surge.sh"
          project: "build"
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
